### ISSUE TITLE
Pro subscription added without paying

### ISSUE THREAD

**Issue by ar1a** [ggtracker/ggtrackerstack#61]
Was looking through the controllers and saw https://github.com/dsjoerg/ggtracker/blob/master/app/controllers/home_controller.rb#L10

went to ggtracker.com/pro_lander and it gave me pro.

**Comment by dsjoerg** [comment]
Thanks for reminding me!

Yep it's set up that way so that when people sign up for Pro, they can immediately start using Pro features.  Otherwise I'd have to wait for Paypal's API to call me and tell me they paid, which for some reason can sometimes take a few minutes.  And why make people wait?

When someone hits pro_lander I get an email, and over the past few years nobody has abused it.

I'm inclined to leave it alone until/unless someone abuses it.

What do you think?

**Comment by ar1a** [comment]
Leave it if it stays unabused. I tried it earlier on (I'm sure you noticed) but then cancelled it :)
